apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-redis  # Nom du composant
  namespace: default
spec:
  type: pubsub.redis  # Type de composant Pub/Sub (Redis)
  metadata:
    - name: redisHost
      value: redis:6380  # Redis accessible sur le port 6380
